FROM openjdk:14.0.2
COPY target/assembly/lama-account-manager-0.1.0-SNAPSHOT.jar /app/lama-account-manager-0.1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "\/app\/lama-account-manager-0.1.0-SNAPSHOT.jar"]
