# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

orbs:
  docker: ledger/docker@volatile
  codecov: codecov/codecov@1.0.2
  
aliases:
  - &filter_all_tags
    tags:
      only: /.*/
  - &restore_docker_cache
    keys:
      - lama-cache-docker-{{ .Branch }}-{{ checksum "build.sbt" }}
      - lama-cache-docker-{{ .Branch }}
      - lama-cache-docker
  - &save_docker_cache
    key: lama-cache-docker-{{ .Branch }}-{{ checksum "build.sbt" }}
    paths:
      - ~/.ivy2
      - ~/.sbt

parameters:
  sbt:
    type: string
    default: SBT_OPTS="-Xss512m" sbt -Dsbt.ivy.home=.ivy2 -sbt-dir .sbt

jobs:
  build:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache: *restore_docker_cache
      - run:
          name: Compile
          command: << pipeline.parameters.sbt >> compile test:compile it:compile
      - save_cache: *save_docker_cache

  scala_linter:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache: *restore_docker_cache
      - run:
          name: Run scalastyle
          command: << pipeline.parameters.sbt >> scalastyle

  unit_tests:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
    steps:
      - checkout
      - restore_cache: *restore_docker_cache
      - run:
          name: Run Account Manager unit tests
          command: << pipeline.parameters.sbt >> accountManager/test
      - run:
          name: Run Bitcoin Service unit tests
          command: << pipeline.parameters.sbt >> btcService/test
      - run:
          name: Run Bitcoin Worker unit tests
          command: << pipeline.parameters.sbt >> btcWorker/test
  package:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
    steps:
      - checkout
      - restore_cache: *restore_docker_cache
      - run:
          name: Package Jar
          command: << pipeline.parameters.sbt >> assembly

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - package:
          requires:
            - build
      - docker/build_image:
          context: githubpkg
          docker_build_target: account-manager
          requires:
            - package
          after_checkout:
            - run:
                name: Assembly
                command: << pipeline.parameters.sbt >> assembly
      - docker/publish_image:
          context: githubpkg
          requires:
            - docker/build_image
