addSbtPlugin("com.eed3si9n"          % "sbt-assembly"  % "0.14.9")
addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-git"       % "1.0.0")
addSbtPlugin("se.marcuslonnberg"     % "sbt-docker"    % "1.5.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"  % "2.0.2")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"    % "5.0.0-RC2")
addSbtPlugin("org.lyranthe.fs2-grpc" % "sbt-java-gen"  % "0.7.3")
